// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIEobu4r57l-lbRm7YqrjgcSRRfYZeWKg',
    appId: '1:473175772830:web:4b3432f84f4a41a07fb58f',
    messagingSenderId: '473175772830',
    projectId: 'spatch1-f97ce',
    authDomain: 'spatch1-f97ce.firebaseapp.com',
    storageBucket: 'spatch1-f97ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnhHpfe4-SDihX2JX7ajB4H1ghrDjKq-w',
    appId: '1:473175772830:android:dea26e431a2e7a447fb58f',
    messagingSenderId: '473175772830',
    projectId: 'spatch1-f97ce',
    storageBucket: 'spatch1-f97ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Z_GLmqqkodIb-J1z-ojlrzyjLp7Dm3Q',
    appId: '1:473175772830:ios:e4acb9d7eedc50a87fb58f',
    messagingSenderId: '473175772830',
    projectId: 'spatch1-f97ce',
    storageBucket: 'spatch1-f97ce.firebasestorage.app',
    iosBundleId: 'com.example.spatchFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Z_GLmqqkodIb-J1z-ojlrzyjLp7Dm3Q',
    appId: '1:473175772830:ios:e4acb9d7eedc50a87fb58f',
    messagingSenderId: '473175772830',
    projectId: 'spatch1-f97ce',
    storageBucket: 'spatch1-f97ce.firebasestorage.app',
    iosBundleId: 'com.example.spatchFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIEobu4r57l-lbRm7YqrjgcSRRfYZeWKg',
    appId: '1:473175772830:web:028d3eef862100e67fb58f',
    messagingSenderId: '473175772830',
    projectId: 'spatch1-f97ce',
    authDomain: 'spatch1-f97ce.firebaseapp.com',
    storageBucket: 'spatch1-f97ce.firebasestorage.app',
  );
}
